-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgm+pRI3cmQGYTEP4A
\nYy9fP5oL1l2guLV+zvVLdldFaIGgCgYIKoZIzj0DAQehRANCAAR42sFWVdP/stT/
\nZ5i+zyLyhYPGabPJM7OJz/xvng/bgitRl27Wl0cGeeeK90n+SVzbza4C2JMpIZs5
\nx/9GRPSN
-----END PRIVATE KEY-----