platform :ios do
  desc "Update provisioning profiles"
  lane :update_provisioning_profiles do
    match(type: "appstore", password: ENV["MATCH_PASSWORD"])
    match(type: "development", password: ENV["MATCH_PASSWORD"])
  end

  desc "Build the app and test IPA, then upload to Sauce Labs"
  lane :build_and_upload do
    setup_ci

    sync_code_signing(
      type: "development",
      app_identifier: 'test.com.firstproject.DemoAsifFastlane',
      readonly: true
    )

    sync_code_signing(
      type: "appstore",
      app_identifier: 'test.com.firstproject.DemoAsifFastlane',
      readonly: true
    )

    # Build the app IPA
    build_app(
      scheme: "DemoApp",
      export_method: "app-store",
      output_directory: "./output",
      output_name: "DemoApp.ipa"
    )

    # Build the test IPA for UI testing
    build_app(
      scheme: "DemoApp",
      configuration: "Debug",
      export_method: "development",
      output_directory: "./output",
      output_name: "DemoAppTest.ipa"
    )

    # Upload to Sauce Labs
    sh "curl -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY -X POST -H 'Content-Type: application/octet-stream' https://api.us-west-1.saucelabs.com/v1/storage/upload --data-binary @./output/DemoAppTest.ipa?overwrite=true"
  end

  desc "Run XCUI tests on Sauce Labs"
  lane :run_xcui_tests_on_sauce_lab do
    scan(
      scheme: "DemoAppUITests",
      devices: ["iPhone 12"],
      derived_data_path: "./output/derived_data",
      output_directory: "./output/test_output",
      result_bundle: true
    )
  end
end
